curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B5LXGG05?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B7VHZX64?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B7KCG406?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B41YBW71?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00BVZ6VF19?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B3B4JF96?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB0031190555?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B8DLY478?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B8K6W529?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B1XG9G04?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B8GPC429?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B8GJF672?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'

