curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B41YBW71?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B7JCD629?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B1XFJ342?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B909HB91?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B0XWN259?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00BVZ6VF19?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B3B4JF96?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B8K6W529?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B8GPC429?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB0006014921?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'
curl -s -L -X GET 'https://lt.morningstar.com/api/rest.svc/9vehuxllxs/security_details/GB00B8JYLC77?viewId=investmentTypeLookup&idtype=isin&languageId=en-GB&currencyId=GBP&responseViewFormat=json' | jq .[]'.Id'

